### ISSUE TITLE
IAM Permissions Fix for WebsiteBucketNameExecutionRole in file efs-file-manager-web.yaml 

### ISSUE THREAD

**Issue by eggoynes** [aws-samples/aws-efs-simple-file-manager#60]
## efs-file-manager-web.yaml
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------
| FAIL F3
|
| Resources: ["WebsiteBucketNameExecutionRole"]
| Line Numbers: [45]
|

**Comment by eggoynes** [comment]
Changed the IAM Policy. 

Before 
```
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['logs:*']
                Resource: 'arn:aws:logs:*:*:*'
```
After

```
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
```
